const CAMPAIGNS_POLLS = [
  {
    id: 1,
    title: 'Apathy',
    subtitle: 'Segun Oroyo Presidential Campaign',
    stat: 'Q1 Popularity Rating for South South Territorial Region',
    status: 'Ongoing',
    ccl: 'Damilola Madashiru',
    location: 'Toll Gate Agbado',
    start_date: '6 Oct, 2021',
    end_date: '10 Nov, 2021',
    status_bg: '#F0DAFB',
  },
  {
    id: 2,
    title: 'Needs Assessment',
    subtitle: 'Segun Oroyo Presidential Campaign',
    stat: 'Q1 Popularity Rating for South South Territorial Region',
    status: 'Draft',
    ccl: 'Damilola Madashiru',
    location: 'Toll Gate Agbado',
    start_date: '6 Oct, 2021',
    end_date: '10 Nov, 2021',
    status_bg: '#FFF8CC',
  },
  {
    id: 3,
    title: 'Popularity Rating',
    subtitle: 'Segun Oroyo Presidential Campaign',
    stat: 'Q1 Popularity Rating for South South Territorial Region',
    status: 'Completed',
    ccl: 'Damilola Madashiru',
    location: 'Toll Gate Agbado',
    start_date: '6 Oct, 2021',
    end_date: '10 Nov, 2021',
    status_bg: '#D4F7DC',
  },
  {
    id: 4,
    title: 'Popularity Rating',
    subtitle: 'Segun Oroyo Presidential Campaign',
    stat: 'Q1 Popularity Rating for South South Territorial Region',
    status: 'Not Started',
    ccl: 'Damilola Madashiru',
    location: 'Toll Gate Agbado',
    start_date: '6 Oct, 2021',
    end_date: '10 Nov, 2021',
    status_bg: '#EDEBE9',
  },
  {
    id: 5,
    title: 'Popularity Rating',
    subtitle: 'Segun Oroyo Presidential Campaign',
    stat: 'Q1 Popularity Rating for South South Territorial Region',
    status: 'Completed',
    ccl: 'Damilola Madashiru',
    location: 'Toll Gate Agbado',
    start_date: '6 Oct, 2021',
    end_date: '10 Nov, 2021',
    status_bg: '#D4F7DC',
  },
  {
    id: 6,
    title: 'Popularity Rating',
    subtitle: 'Segun Oroyo Presidential Campaign',
    stat: 'Q1 Popularity Rating for South South Territorial Region',
    status: 'Not Started',
    ccl: 'Damilola Madashiru',
    location: 'Toll Gate Agbado',
    start_date: '6 Oct, 2021',
    end_date: '10 Nov, 2021',
    status_bg: '#EDEBE9',
  },
  {
    id: 7,
    title: 'Popularity Rating',
    subtitle: 'Segun Oroyo Presidential Campaign',
    stat: 'Q1 Popularity Rating for South South Territorial Region',
    status: 'Completed',
    ccl: 'Damilola Madashiru',
    location: 'Toll Gate Agbado',
    start_date: '6 Oct, 2021',
    end_date: '10 Nov, 2021',
    status_bg: '#D4F7DC',
  },
  {
    id: 8,
    title: 'Popularity Rating',
    subtitle: 'Segun Oroyo Presidential Campaign',
    stat: 'Q1 Popularity Rating for South South Territorial Region',
    status: 'Not Started',
    ccl: 'Damilola Madashiru',
    location: 'Toll Gate Agbado',
    start_date: '6 Oct, 2021',
    end_date: '10 Nov, 2021',
    status_bg: '#EDEBE9',
  },
];

export default CAMPAIGNS_POLLS;
