const results = [
  {
    id: 1,
    title: '2022 Presidential Campaign for Mitchel',
    type: 'Presidential',
    name: 'Godwin Amefiele',
    campaign: '12',
    year: '2023',
    status: 'ACTIVE',
    names: 'Godwin Amefiele',
    campaigns: '12',
    years: '2023',
    statuss: 'ACTIVE',
  },
  {
    id: 2,
    title: '2022 Presidential Campaign for Mitchel',
    type: 'Gubernatorial',
    name: 'Godwin Amefiele',
    campaign: '12',
    year: '2024',
    status: 'DEACTIVATED',
    names: 'Godwin Amefiele',
    campaigns: '12',
    years: '2023',
    statuss: 'ACTIVE',
  },
  {
    id: 3,
    title: '22022 Presidential Campaign for Mitchel',
    type: 'Senatorial',
    name: 'Aminu Tambuwal',
    campaign: '12',
    year: '2024',
    status: 'ACTIVE',
    names: 'Godwin Amefiele',
    campaigns: '12',
    years: '2023',
    statuss: 'ACTIVE',
  },
  {
    id: 4,
    title: '2022 Presidential Campaign for Mitchel',
    type: 'Councilorship',
    name: 'Olayemi Osinbajo',
    campaign: '12',
    year: '2023',
    status: 'INACTIVE',
    names: 'Godwin Amefiele',
    campaigns: '12',
    years: '2023',
    statuss: 'ACTIVE',
  },
  {
    id: 5,
    title: '2022 Presidential Campaign for Mitchel',
    type: 'Chairmanship',
    name: 'Godwin Amefiele',
    campaign: '12',
    year: '2023',
    status: 'DEACTIVATED',
    names: 'Godwin Amefiele',
    campaigns: '12',
    years: '2023',
    statuss: 'ACTIVE',
  },
  {
    id: 6,
    title: '2022 Presidential Campaign for Mitchel',
    type: 'Presidential',
    name: 'Godwin Amefiele',
    campaign: '12',
    year: '2023',
    status: 'Draft',
    names: 'Godwin Amefiele',
    campaigns: '12',
    years: '2023',
    statuss: 'ACTIVE',
  },
  {
    id: 7,
    title: '2022 Presidential Campaign for Mitchel',
    type: 'House of Reps',
    name: 'Godwin Amefiele',
    campaign: '12',
    year: '2023',
    status: 'ACTIVE',
    names: 'Godwin Amefiele',
    campaigns: '12',
    years: '2023',
    statuss: 'ACTIVE',
  },
  {
    id: 8,
    title: '2022 Presidential Campaign for Mitchel',
    type: 'House of Assembly',
    name: 'Godwin Amefiele',
    campaign: '12',
    year: '2023',
    status: 'DEACTIVATED',
    names: 'Godwin Amefiele',
    campaigns: '12',
    years: '2023',
    statuss: 'ACTIVE',
  },
  {
    id: 9,
    title: '2022 Presidential Campaign for Mitchel',
    type: 'House of Assembly',
    name: 'Godwin Amefiele',
    campaign: '12',
    year: '2023',
    status: 'DEACTIVATED',
    names: 'Godwin Amefiele',
    campaigns: '12',
    years: '2023',
    statuss: 'ACTIVE',
  },
  {
    id: 10,
    title: '2022 Presidential Campaign for Mitchel sunday skskdkd',
    type: 'House of Assembly',
    name: 'Godwin Amefiele',
    campaign: '12',
    year: '2023',
    status: 'DEACTIVATED',
    names: 'Godwin Amefiele',
    campaigns: '12',
    years: '2023',
    statuss: 'ACTIVE',
  },
  {
    id: 11,
    title: '2022 Presidential Campaign for Mitchel',
    type: 'House of Assembly',
    name: 'Godwin Amefiele',
    campaign: '12',
    year: '2023',
    status: 'DEACTIVATED',
    names: 'Godwin Amefiele',
    campaigns: '12',
    years: '2023',
    statuss: 'ACTIVE',
  },
  {
    id: 12,
    title: '2022 Presidential Campaign for Mitchel',
    type: 'House of Assembly',
    name: 'Godwin Amefiele',
    campaign: '12',
    year: '2023',
    status: 'DEACTIVATED',
    names: 'Godwin Amefiele',
    campaigns: '12',
    years: '2023',
    statuss: 'ACTIVE',
  },
  {
    id: 13,
    title: '2022 Presidential Campaign for Mitchel',
    type: 'House of Assembly',
    name: 'Godwin Amefiele',
    campaign: '12',
    year: '2023',
    status: 'DEACTIVATED',
    names: 'Godwin Amefiele',
    campaigns: '12',
    years: '2023',
    statuss: 'ACTIVE',
  },
  {
    id: 14,
    title: '2022 Presidential Campaign for Mitchel',
    type: 'House of Assembly',
    name: 'Godwin Amefiele',
    campaign: '12',
    year: '2023',
    status: 'DEACTIVATED',
    names: 'Godwin Amefiele',
    campaigns: '12',
    years: '2023',
    statuss: 'ACTIVE',
  },
  {
    id: 15,
    title: '2022 Presidential Campaign for Mitchel',
    type: 'House of Assembly',
    name: 'Godwin Amefiele',
    campaign: '12',
    year: '2023',
    status: 'DEACTIVATED',
    names: 'Godwin Amefiele',
    campaigns: '12',
    years: '2023',
    statuss: 'ACTIVE',
  },
  {
    id: 16,
    title: '2022 Presidential Campaign for Mitchel',
    type: 'House of Assembly',
    name: 'Godwin Amefiele',
    campaign: '12',
    year: '2023',
    status: 'DEACTIVATED',
    names: 'Godwin Amefiele',
    campaigns: '12',
    years: '2023',
    statuss: 'ACTIVE',
  },
  {
    id: 17,
    title: '2022 Presidential Campaign for Mitchel',
    type: 'House of Assembly',
    name: 'Godwin Amefiele',
    campaign: '12',
    year: '2023',
    status: 'DEACTIVATED',
    names: 'Godwin Amefiele',
    campaigns: '12',
    years: '2023',
    statuss: 'ACTIVE',
  },
];

const filters = [
  {
    label: 'Poll type',
    backgrounColor: '#1E0A3C',
    options: [
      // { id: 'Presidential', value: 'Presidential' },
      // { id: 'Gubernatorial', value: 'Gubernatorial' },
      // { id: 'Senatorial', value: 'Senatorial' },
      // { id: 'House of Representatives', value: 'House of Representatives' },
      // { id: 'House of Assembly', value: 'House of Assembly' },
      // { id: 'Chairmanship', value: 'Chairmanship' },
      // { id: 'Councilorship', value: 'Councilorship' },
      {
        id: 'Candidate Popularity',
        value: 'Candidate Popularity',
      },
      {
        id: 'Party Popularity',
        value: 'Party Popularity',
      },
      {
        id: 'Generic',
        value: 'Generic',
      },
    ],
  },
  {
    label: 'Status',
    options: [
      { id: 'ONGOING', value: 'Ongoing' },
      { id: 'ACTIVE', value: 'Active' },
      { id: 'DEACTIVATED', value: 'Deactivated' },
    ],
  },
];

const polls = [
  {
    label: 'Status: All',
    options: [
      { id: 'Ongoing', value: 'Ongoing' },
      { id: 'Not Started', value: 'Not Started' },
      { id: 'Draft', value: 'Draft' },
      { id: 'Completed', value: 'Completed' },
    ],
    backgroundColor: true,
  },
  {
    label: 'Poll Type',
    options: [
      { id: 'POPULARITY STAR_RATING', value: 'Popularity Rating' },
      { id: 'NEEDS', value: 'Needs' },
      { id: 'DRAFT', value: 'Draft' },
      { id: 'COMPLETED', value: 'Completed' },
    ],
  },
];

const columns = [
  {
    label: 'Title',
    key: 'title',
    sort: true,
    minWidth: 250,
  },
  {
    label: 'Campaign Type',
    key: 'type',
    sort: true,
    minWidth: 170,
  },
  {
    label: "Candidate's name",
    key: 'name',
    minWidth: 250,
  },
  {
    label: 'No. of Polls',
    key: 'campaign',
    minWidth: 120,
  },
  {
    label: 'Year',
    key: 'year',
    minWidth: 100,
  },
  {
    label: 'Status',
    key: 'status',
    minWidth: 170,
  },
];

const ELECTION_TYPE = [
  { label: 'Presidential', value: 'PRESIDENTIAL' },
  { label: 'Gubernatorial', value: 'GUBERNATORIAL' },
  { label: 'Senatorial', value: 'SENATORIAL' },
  { label: 'House of Representative', value: 'HOUSE_OF_REPRESENTATIVE' },
  { label: 'House of Assembly', value: 'HOUSE_ASSEMBLY' },
  { label: 'Chairmanship', value: 'CHAIRMANSHIP' },
  { label: 'Councilorship', value: 'COUNCILLORSHIP' },
];

const POLL_TYPE = [
  {
    name: 'Candidate Popularity',
    value: 'CANDIDATE_POPULARITY',
  },
  {
    name: 'Party Popularity',
    value: 'PARTY_POPULARITY',
  },
  {
    name: 'Generic',
    value: 'GENERIC',
  },
];

const CAMPAIGN_MANAGER = ['Mona Kane', 'Harry Kane'];

const ELECTION_YEAR = ['2021', '2022', '2023', '2024', '2024', '2025'];

const MANAGE_ELECTION_COUNTER = [
  { id: 1, name: 'Campaign Details' },
  { id: 2, name: 'Opposition Details' },
  { id: 3, name: 'Preview' },
];
const ADD_POLL_COUNTER = [
  { id: 1, name: 'Details' },
  { id: 2, name: 'Polls' },
  { id: 3, name: 'Target' },
  { id: 4, name: 'Preview' },
];

const CAMPAIGN_TYPES = {
  HOUSE_OF_ASSEMBLY: 'House of Assembly',
  CHAIRMANSHIP: 'Chairmanship',
  COUNCILORSHIP: 'Councilorship',
  GUBERNATORIAL: 'Gubernatorial',
  HOUSE_OF_REPRESENTATIVE: 'House of Representative',
  PRESIDENTIAL: 'Presidential',
  SENATORIAL: 'Senatorial',
};

export {
  ELECTION_TYPE,
  CAMPAIGN_MANAGER,
  ELECTION_YEAR,
  MANAGE_ELECTION_COUNTER,
  filters,
  columns,
  polls,
  results,
  POLL_TYPE,
  ADD_POLL_COUNTER,
  CAMPAIGN_TYPES,
};
