const Roles = {
  SUPERADMIN: 'SUPER_ADMIN',
  ADMIN: 'ADMIN',
  CALLGROUPAGENT: 'CALL_GROUP_AGENT',
  CALLGROUPMANAGER: 'CALL_GROUP_MANAGER',
  CALLGROUPLEAD: 'CALL_GROUP_LEAD',
  INBOUNDAGENT: 'INBOUND_AGENT',
  OUTBOUNDAGENT: 'OUTBOUND_AGENT',
  CAMPAIGNMANAGER: 'CAMPAIGN_MANAGER',
  CANDIDATE: 'CANDIDATE',
  PARTYAGENT: 'PARTY_AGENT',
  CALLGROUPLEADOUTBOUND: 'CALL_GROUP_LEAD',
};

export default Roles;
