const DATA = [
  {
    id: 1,
    pollName: 'Segun Oroyo Presidential Poll',
    rating: 'Q1 Popularity Rating For South-South Territorial Region',
    timeline: 100,
    status: 'Complete',
    title: 'Apathy',
    start_date: '6 Oct, 2021',
    end_date: '10 Nov, 2021',
  },
  {
    id: 2,
    pollName: 'Segun Oroyo Presidential Poll',
    rating: 'Q1 Popularity Rating For South-South Territorial Region',
    timeline: 80,
    status: 'Ongoing',
    title: 'Candidate Popularity Rating',
    start_date: '6 Oct, 2021',
    end_date: '10 Nov, 2021',
  },
  {
    id: 3,
    pollName: 'Segun Oroyo Presidential Poll',
    rating: 'Q1 Popularity Rating For South-South Territorial Region',
    timeline: 50,
    status: 'Ongoing',
    title: 'Apathy',
    start_date: '6 Oct, 2021',
    end_date: '10 Nov, 2021',
  },
  {
    id: 4,
    pollName: 'Segun Oroyo Presidential Poll',
    rating: 'Q1 Popularity Rating For South-South Territorial Region',
    timeline: 100,
    status: 'Complete',
    title: 'Party Popularity Rating',
    start_date: '6 Oct, 2021',
    end_date: '10 Nov, 2021',
  },
  {
    id: 5,
    pollName: 'Segun Oroyo Presidential Poll',
    rating: 'Q1 Popularity Rating For South-South Territorial Region',
    timeline: 100,
    status: 'Complete',
    title: 'Needs Assessment',
    start_date: '6 Oct, 2021',
    end_date: '10 Nov, 2021',
  },
  {
    id: 6,
    pollName: 'Segun Oroyo Presidential Poll',
    rating: 'Q1 Popularity Rating For South-South Territorial Region',
    timeline: 100,
    status: 'Complete',
    title: 'Needs Assessment',
    start_date: '6 Oct, 2021',
    end_date: '10 Nov, 2021',
  },
  {
    id: 7,
    pollName: 'Segun Oroyo Presidential Poll',
    rating: 'Q1 Popularity Rating For South-South Territorial Region',
    timeline: 99,
    status: 'Ongoing',
    title: 'Apathy',
    start_date: '6 Oct, 2021',
    end_date: '10 Nov, 2021',
  },
  {
    id: 8,
    pollName: 'Segun Oroyo Presidential Poll',
    rating: 'Q1 Popularity Rating For South-South Territorial Region',
    timeline: 70,
    status: 'Ongoing',
    title: 'Party Popularity Rating',
    start_date: '6 Oct, 2021',
    end_date: '10 Nov, 2021',
  },
  {
    id: 9,
    pollName: 'Segun Oroyo Presidential Poll',
    rating: 'Q1 Popularity Rating For South-South Territorial Region',
    timeline: 100,
    status: 'Complete',
    title: 'Party Popularity Rating',
    start_date: '6 Oct, 2021',
    end_date: '10 Nov, 2021',
  },
  {
    id: 10,
    pollName: 'Segun Oroyo Presidential Poll',
    rating: 'Q1 Popularity Rating For South-South Territorial Region',
    timeline: 65,
    status: 'Ongoing',
    title: 'Apathy',
    start_date: '6 Oct, 2021',
    end_date: '10 Nov, 2021',
  },
  {
    id: 12,
    pollName: 'Segun Oroyo Presidential Poll',
    rating: 'Q1 Popularity Rating For South-South Territorial Region',
    timeline: 100,
    status: 'Complete',
    title: 'Candidate Popularity Rating',
    start_date: '6 Oct, 2021',
    end_date: '10 Nov, 2021',
  },
  {
    id: 13,
    pollName: 'Segun Oroyo Presidential Poll',
    rating: 'Q1 Popularity Rating For South-South Territorial Region',
    timeline: 100,
    status: 'Complete',
    title: 'Candidate Popularity Rating',
    start_date: '6 Oct, 2021',
    end_date: '10 Nov, 2021',
  },
];

export default DATA;
