const DATA = [
  {
    id: 1,
    pollName: 'Segun Oroyo Presidential Poll',
    rating: 'Segun Oroyo Presidential Poll',
    timeline: 23,
    status: 'Ongoing',
    title: 'Presidential',
    start_date: '6 Oct, 2021',
    end_date: '10 Nov, 2021',
    counts: 1,
  },
  {
    id: 2,
    pollName: 'Segun Oroyo Presidential Poll',
    rating: 'Segun Oroyo Presidential Poll',
    timeline: 80,
    status: 'Ongoing',
    title: 'Honourable',
    start_date: '6 Oct, 2021',
    end_date: '10 Nov, 2021',
    counts: 3,
  },
  {
    id: 3,
    pollName: 'Segun Oroyo Presidential Poll',
    rating: 'Segun Oroyo Presidential Poll',
    timeline: 50,
    status: 'Ongoing',
    title: 'Presidential',
    start_date: '6 Oct, 2021',
    end_date: '10 Nov, 2021',
    counts: 2,
  },
  {
    id: 4,
    pollName: 'Segun Oroyo Presidential Poll',
    rating: 'Segun Oroyo Presidential Poll',
    timeline: 100,
    status: 'Ongoing',
    title: 'Gubernatorial',
    start_date: '6 Oct, 2021',
    end_date: '10 Nov, 2021',
    counts: 3,
  },
  {
    id: 5,
    pollName: 'Segun Oroyo Presidential Poll',
    rating: 'Segun Oroyo Presidential Poll',
    timeline: 30,
    status: 'Ongoing',
    title: 'Senetorial',
    start_date: '6 Oct, 2021',
    end_date: '10 Nov, 2021',
    counts: 1,
  },
  {
    id: 6,
    pollName: 'Segun Oroyo Presidential Poll',
    rating: 'Segun Oroyo Presidential Poll',
    timeline: 100,
    status: 'Ongoing',
    title: 'Senetorial',
    start_date: '6 Oct, 2021',
    end_date: '10 Nov, 2021',
    counts: 3,
  },
  {
    id: 7,
    pollName: 'Segun Oroyo Presidential Poll',
    rating: 'Segun Oroyo Presidential Poll',
    timeline: 69,
    status: 'Ongoing',
    title: 'Presidential',
    start_date: '6 Oct, 2021',
    end_date: '10 Nov, 2021',
    counts: 2,
  },
  {
    id: 8,
    pollName: 'Segun Oroyo Presidential Poll',
    rating: 'Segun Oroyo Presidential Poll',
    timeline: 70,
    status: 'Ongoing',
    title: 'Gubernatorial',
    start_date: '6 Oct, 2021',
    end_date: '10 Nov, 2021',
    counts: 3,
  },
  {
    id: 9,
    pollName: 'Segun Oroyo Presidential Poll',
    rating: 'Segun Oroyo Presidential Poll',
    timeline: 100,
    status: 'Ongoing',
    title: 'Gubernatorial',
    start_date: '6 Oct, 2021',
    end_date: '10 Nov, 2021',
    counts: 3,
  },
  {
    id: 10,
    pollName: 'Segun Oroyo Presidential Poll',
    rating: 'Segun Oroyo Presidential Poll',
    timeline: 65,
    status: 'Ongoing',
    title: 'Presidential',
    start_date: '6 Oct, 2021',
    end_date: '10 Nov, 2021',
    counts: 2,
  },
  {
    id: 12,
    pollName: 'Segun Oroyo Presidential Poll',
    rating: 'Segun Oroyo Presidential Poll',
    timeline: 100,
    status: 'Ongoing',
    title: 'Honourable',
    start_date: '6 Oct, 2021',
    end_date: '10 Nov, 2021',
    counts: 3,
  },
  {
    id: 13,
    pollName: 'Segun Oroyo Presidential Poll',
    rating: 'Segun Oroyo Presidential Poll',
    timeline: 100,
    status: 'Ongoing',
    title: 'Honourable',
    start_date: '6 Oct, 2021',
    end_date: '10 Nov, 2021',
    counts: 3,
  },
];

export const WORKBENCH_PROGRESS_STATUS_BG = {
  Ongoing: '#F0DAFB',
  Completed: 'rgba(95, 210, 85, 0.2)',
};

export default DATA;
